version: '2'

services:
  shibboleth_sp:
    build: .
    restart: always
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./secrets/:/run/secrets
    environment:
      sp_idp: "https://shib-test.bu.edu/idp/shibboleth"
      SERVER_NAME: "localhost"
