version: '2'

services:
  shibboleth_sp:
    #image: shib-sp-test
    build: .
    restart: always
    links:
      - phpbin
    ports:
      - "8000:80"
    networks:
      - phpapp
    depends_on:
      - phpbin
    #volumes:
    #  - ./init:/docker-entrypoint-initdb.d
    #  - data:/var/lib/postgres/data
    secrets:
      - SHIB_SP_KEY
      - SHIB_SP_CERT
    environment:
      sp_idp: "https://shib.bu.edu/idp/shibboleth"
  phpbin:
    build: test/phpbin/
    restart: always
    #environment:
    networks:
      - phpapp
    
#volumes:
#  data:
#    driver: local

networks:
  phpapp:
    driver: bridge

# The following is how to reference 
#
secrets:
  SHIB_SP_KEY:
    external: true
  SHIB_SP_CERT:
    external: true
